### ISSUE TITLE
Possible method naming inconsistency

### ISSUE THREAD

**Issue by donners77** [HeadspringLabs/Enumeration#22]
Hi. Thanks for making this library available.  I'm finding it really useful.

I noticed a possible method naming inconsistency relating to Try/FromValue versus Try/Parse.

The public parse methods take a string input while the one public FromValue method takes a TValue input.

If there is a public naming convention that parsing means converting a string and 'from value' means converting a value...

Then I'm wondering if the method `public static bool TryParse(TValue value, out TEnumeration result)` should be named  `public static bool TryFromValue(TValue value, out TEnumeration result)` 

However, this would be a breaking change and may be too pedantic.

**Comment by pedroreys** [comment]
hey, this issue has been here for a *really* long time. Sorry for the delay :)
I understand where you are coming from, and I even agree with you on that. 

Unfortunately, like you said, this would be a breaking change and I believe the costs of such change outweigh its benefits in this particular case.
