### ISSUE TITLE
How to preform next, previous

### ISSUE THREAD

**Issue by weedkiller** [HeadspringLabs/Enumeration#26]
Hi, I just found your lib,  I am trying to replace the traditional Enum with a something that supports moving through and preforming operations/verbs based on the enum values

I'm outside a for/foreach loop, and would like to `increment` an Enum for e.g `Submitted` to `Approved` 
**how could I move through the enums**

```
   Document.Status.Next()  // success/true, if false it was the last enum.
   Document.Status.NextOrLast()  //
   Document.Status.Previous()  //
   Document.Status.PreviousOrFirst()  //
```

**Can I set a status from string**, `Document.Status = "Approved";`?

thanks

**Comment by plioi** [comment]
We'll need more details to know what you're trying to accomplish.  Can you post the definition of the enumeration, and a failing test which demonstrates what's not working for you?

**Comment by weedkiller** [comment]
I was asking to moving through the Enum, for e.g. I wanted to move the status to next state of Enum in the list.

Like Draft to Submit state

**Comment by plioi** [comment]
Each enumeration object should be immutable (read-only state). But, they can have methods like any other class. You could write a method GetNextState() which considers "this" to decide what to return.

public State GetNextState(){
    if (this == Submitted) return Approved;
    //etc...
}
