### ISSUE TITLE
Different instance object's Enumeration property point to the same memory address?

### ISSUE THREAD

**Issue by hanslai** [HeadspringLabs/Enumeration#27]
I am not sure if this is expected behavior or I miss something, I wrote a small console sample program to Illustrate the problem.

I created two employees which should have its own enumeration EmploymentState 
 which has a DateEmploymentStarted property.

As the main program's output shows below.  When I set employee 2's DateEmploymentStarted, it will over write employee 1's DateEmploymentStarted as well.

So, seem like all the employees are actually point to the same EmploymentState object memory address.  But EmploymentState class is not static.  

```c#
public class EmploymentState : Enumeration<EmploymentState, int>
    {
        private EmploymentState() : base(0, "") { }
        private EmploymentState(int value, string displayName) : base(value, displayName) { }
        public DateTimeOffset DateEmploymentStarted { get; set; }
       
        public static readonly EmploymentState Employed = new EmploymentState(0, $"Empployed");
        public static readonly EmploymentState Probration = new EmploymentState(1, $"Probration");
        public static readonly EmploymentState Terminated = new EmploymentState(2, $"Terminated");
    }
```
Employee Class
```c#
    public sealed class Employee 
    {
        private Employee() { }
        public Guid Id { get; private set; }
        public string Name { get; private set; }
        public EmploymentState EmployementState { get; private set; }

        public static Employee Create(string name)
        {
            return new Employee
            {
                Id = Guid.NewGuid(),
                Name = name
            };
        }
        public void SetEmploymentStateToEmployed(DateTimeOffset employmentStartedDate)
        {
            EmployementState = EmploymentState.Employed;
            EmployementState.DateEmploymentStarted = employmentStartedDate;
        }
    }
```
Main Program
```c#
    class Program
    {
        static void Main(string[] args)
        {
            Employee e1 = Employee.Create("employee 1");
            Employee e2 = Employee.Create("employee 2");

            e1.SetEmploymentStateToEmployed(employmentStartedDate: new DateTimeOffset(new DateTime(1111, 1, 1)));
            e2.SetEmploymentStateToEmployed(employmentStartedDate: new DateTimeOffset(new DateTime(2222, 2, 2)));

            Console.WriteLine($"{e1.Name} employed date: {e1.EmployementState.DateEmploymentStarted}");
            Console.WriteLine($"{e2.Name} employed date: {e2.EmployementState.DateEmploymentStarted}");
            Console.ReadKey();
        }
    }
```
output: 
```
employee 1 employed date: 2/2/2222 12:00:00 AM +08:00
employee 2 employed date: 2/2/2222 12:00:00 AM +08:00
```

I know I can easily move DateEmploymentStarted out of the EmploymentState class and have the problem solved.  But I would still like to know why setting the second employee's enumeration's property will over write the first one's enumeration's property.

Thank you for you help.

**Comment by volak** [comment]
`EmploymentState.Employed;`
Is a static instance and you set start date on the same instance twice.

Enum properties are not meant to be mutable.  They are set once at creation and never changed.

**Comment by hanslai** [comment]
@volak Thank you for your quick reply.  But I am not sure I understand, I did set EmploymentState.Employed twice but to **two different instances** of employee e1 and e2.  I updated my simple program a bit above to better explain myself with the problem. 

I added a SetEmploymentStateToProbration() in order to set different employee to probration states
```C#
       public void SetEmploymentStateToProbration(DateTimeOffset employmentStartedDate)
        {
            EmployementState = EmploymentState.Probration;
            EmployementState.DateEmploymentStarted = employmentStartedDate;
        }
```
and updated the main program as following.
```c#
e1.SetEmploymentStateToEmployed(employmentStartedDate: new DateTimeOffset(new DateTime(1111, 1, 1)));
e2.SetEmploymentStateToEmployed(employmentStartedDate: new DateTimeOffset(new DateTime(2222, 2, 2)));
e2.SetEmploymentStateToProbration(employmentStartedDate: new DateTimeOffset(new DateTime(3333, 3, 3)));

Console.WriteLine($"{e1.Name} State = {e1.EmployementState}, Employment Started Date = {e1.EmployementState.DateEmploymentStarted}");
Console.WriteLine($"{e2.Name} State = {e2.EmployementState}, Employment Started Date = {e2.EmployementState.DateEmploymentStarted}");
Console.ReadKey();
```
output 
```
employee 1 State = Empployed, Employment Started Date = 2/2/2222 12:00:00 AM +08:00
employee 2 State = Probration, Employment Started Date = 3/3/3333 12:00:00 AM +08:00
```
both `SetEmploymentStateToEmployed()` and `SetEmploymentStateToProbration()` should change its own empoyee's `EmployementState.DateEmploymentStarted` date.

but when I called **e2**  `e2.SetEmploymentStateToEmployed()`, it also change **e1**'s _EmployementState.DateEmploymentStarted_ value to e2's value, which is  DateTime(2222, 2, 2)

but when I called `e2.SetEmploymentStateToProbration()` , e1's _EmployementState.DateEmploymentStarted_ does not get changed.

why calling `e2.SetEmploymentStateToEmployed()` will change e1's _EmployementState.DateEmploymentStarted_, that confused me.

Thanks for your help.

**Comment by volak** [comment]
`EmployementState = EmploymentState.Employed`
this doesn't create an instance, its referencing a static instance.

`e1` and `e2` are using the same instance of `EmploymentState`

**Comment by plioi** [comment]
The purpose of Enumeration is to provide a small, finite set of instances of a type, *limiting* the ability to create other instances. If you want new instances of a class, discard Enumeration and just construct them with "new".

Also, imagine how frustrating C# would be if every time you *look* at a "static readonly" reference, it *changed* to some other instance.

**Comment by hanslai** [comment]
Thank you @volak @plioi
